---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: busybox
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./busybox/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

