---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
  interval: 1m0s
  releaseName: linkerd
  targetNamespace: linkerd
  valuesFrom:
  - kind: Secret
    name: linkerd-certs

