---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: busybox
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./“./busybox
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-lab
  validation: client

